### ISSUE TITLE
Suggestions not working

### ISSUE THREAD

**Issue by tobia** [sublimelsp/LSP-yaml#18]
**To Reproduce**
1. Close ST3, rename away your ~/.config/sublime-text-3` directory, and reopen ST3
2. Install Package control from the command palette
3. Install LSP and LSP-yaml packages; restart ST3
4. Open or create a yaml file with a `$schema:` declaration at the top (see example below); restart ST3 again for good measure
5. Place your cursor in any place where a fixed set of keys are expected and start writing

**Expected behavior**
The available keys according to the schema should be shown in the suggestion menu.

**Actual behaviour**
Either nothing is shown, or ST3's default menu based on the other words present in the file.

**Example**
Here is a yaml file with a valid schema:

```yaml
$schema: https://vega.github.io/schema/vega-lite/v4.json
description: A simple bar chart
data:
  values:
    - { a: A, b: 28 }
    - { a: B, b: 55 }
    - { a: C, b: 43 }
mark: bar
encoding:
  x: 
    field: a
    type: nominal
    axis: 
      labelAngle: 0
  y: 
    field: b
    type: quantitative
  # <- here
```

If you place your cursor where the comment is shown, aligned with `y:`, and start typing `col`... it should suggest `color`, but instead nothing is suggested.
